GSOC-22:Ver 1-S3 Upload Script
jitsi/jitsi-upload-integrations pull request #24
Opened 2022-08-07 06:19 UTC by ag-cdev

Status:

S3 Upload is Working only need one params that is passed through the shell script.

Next Task:

Looking to enable renamer of files to better organize it.
Slowly remove the shell script as a whole after other cloud's like dropbox, gdrive are integrated.

2022-09-11 15:04 UTC, ag-cdev commented
Uploads Working:
S3
Dropbox
Box

2022-09-12 18:52 UTC, aaronkvanmeerten requested changes
most of this looks like good, a few comments and we can merge it.

2022-09-12 18:52 UTC, aaronkvanmeerten commented on magic_script.py
> +CONFIGFILE = "/mnt/gsoc/test/s3/config.json"
Please do not hardcode paths like this in your scripts.  This should assume a relative path of the present directory.

2022-09-12 18:52 UTC, aaronkvanmeerten commented on magic_script.py
> +import json
Please rename this script to python_uploader.py

2022-09-12 18:52 UTC, aaronkvanmeerten commented on config.json
> +{
Please rename this to config.json.example to avoid actually having it parsed by your code, since its' not actually safe for everyone.

2022-09-14 10:57 UTC, ag-cdev commented
Please check all changes done @aaronkvanmeerten

2023-03-23 00:44 UTC, palmtown commented
> Please check all changes done @aaronkvanmeerten

The status of this PR appears to be still "1 review requesting changes."  Can you push it to review?  Also, how to install and use this with s3?

2023-03-24 16:25 UTC, aaronkvanmeerten commented
This was a gsoc project which has not had any attention since last year, I am closing it for now but leaving the branch in case anyone is interested in the implementation.

2023-03-24 16:25 UTC, closed without merging

2023-03-24 16:26 UTC, aaronkvanmeerten commented
> > Please check all changes done @aaronkvanmeerten
> 
> The status of this PR appears to be still "1 review requesting changes." Can you push it to review? Also, how to install and use this with s3?

Sorry to say I'm not sure how to configure it with s3 and am lacking the available time to document or support it.  Feel free to review the code on the branch and see if it's of use to you, and you could install it over the existing .deb installer version.